### ISSUE TITLE
Data Requirements

### ISSUE THREAD

**Issue by sevamoo** [dubvulture/tensor_fcn#1]
Hi, thanks for sharing.
Could you please, provide some info on the data requirements and its format. apparently, the ADEchallenge data is no longer available. 
Thanks in advance.
Best

**Comment by dubvulture** [comment]
Uh, that sucks. I'll see if I can upload it somewhere (but it'll take sometime given my upload speed).

Anyway, the general image formats are simple:
- **images**: RGB/BGR image (for grayscale you have to change the `3` in [fcn.py](https://github.com/dubvulture/tensor_fcn/blob/97c0d9571b6b47252e9adc71e36cd45f635cb4a7/tensor_fcn/fcn.py#L32) to a `1`)
- **annotations**: grayscale image with values in `[0, number_of_classes)` (so you're limited to 255 classes currently, but it's possibile to surpass this limit with some tinkering)

Note: the annotations are not required.
Let's say you have a custom dataset with some external reference describing the polygons of the objects (for example a json or mat file). In that case while creating your own subclass of [dataset_reader.py](https://github.com/dubvulture/tensor_fcn/tree/master/tensor_fcn/dataset_reader/dataset_reader.py) you could pass that structure to your class' constructor and generate the annotated images at runtime overriding `_get_image` accordingly.

Anyway with the ADE dataset the annotations were already available as images and after downloading the files were rearranged as 
```
| ADEChallengeData2016/
    | train/
        | images/
        | annotations/
    | val/
        | images/
        | annotations/
```
Note: each image in `X/images/` had a corresponding annotated image in `X/annotations/` with the same name. Only the extension was different (jpg for the image, png for the annotations)

[ade_dataset.py](https://github.com/dubvulture/tensor_fcn/tree/master/tensor_fcn/dataset_reader/ade_dataset.py) takes one of the directories containing `images/` and `annotations/` as the first argument (`ade_dir`).
If you want to specify a subset you can pass a list of filenames  as `fnames` (no file extension) that can be found in both `images/` and `annotations/`

I hope this helps.


EDIT: the link seems to be online again
